language: node_js
node_js:
  - "10"
script: npm test
deploy:
  provider: pages
  edge: true
  local-dir: release
  repo: dwst/dwst.github.io
  target-branch: master
  github-token: $GITHUB_TOKEN
  commit-message: "Deploy %{git_tag} %{git_commit_msg}%"
  on:
    repo: dwst/dwst
    all_branches: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
